---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: document
  path: config.toml
  label: Configuration
  read_only: false
- type: heading
  label: Content
- type: directory
  path: hugo/content
  label: Pages
  create: all
  match: "*"
- type: directory
  path: hugo/content/careers
  label: Careers
  create: all
  match: "**/*"
- type: directory
  path: hugo/content/showcase
  label: Showcase
  create: all
  match: "**/*"
- type: directory
  path: hugo/content/blog
  label: Blog
  create: all
  match: "**/*"
- type: heading
  label: Documentation
- type: directory
  path: hugo/content/docs
  label: Docs
  create: all
  match: "**/*"
  exclude: "{changelog,sunset}/*"
- type: directory
  path: hugo/content/docs/changelog
  label: Changelog
  create: all
  match: "*"
  templates:
  - changelog
- type: directory
  path: hugo/content/docs/sunset
  label: Sunset Notices
  create: all
  match: "*"
upload_dir: hugo/static/uploads
public_path: "/uploads"
front_matter_path: "/uploads"
use_front_matter_path: false
file_template: ":year:/:month:/:filename:"
version: '0.49'
